version: "3.8"
services:
  xmpp-sv:
    restart: always
    hostname: xmpp-sv
    image: mongooseim/mongooseim:4.1.0
    container_name: mongooseim
    environment:
      JOIN_CLUSTER: "false"
    volumes:
      - ./mongooseim/cfg:/member
  xmpp-sv-2:
    restart: always
    depends_on:
      - xmpp-sv
    hostname: xmpp-sv-2
    image: mongooseim/mongooseim:4.1.0
    container_name: mongooseim-2
    environment:
      CLUSTER_WITH: "mongooseim@xmpp-sv"
  nginx:
    restart: always
    depends_on:
      - xmpp-sv
    image: nginx:1.19
    container_name: was
    volumes:
      - ./nginx-mongooseim/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./stanza/examples:/usr/share/nginx/html:ro
      - ./stanza/dist:/usr/share/nginx/dist:ro
    ports:
      - 80:80
