version: "3.8"
services:
  xmpp-sv:
    image: mongooseim/mongooseim:4.1.0
    container_name: mongooseim
    environment:
      JOIN_CLUSTER: "false"
    volumes:
      - ./mongooseim/cfg:/member
    restart: always
  nginx:
    depends_on:
      - xmpp-sv
    image: nginx:1.19
    container_name: was
    restart: always
    volumes:
      - ./nginx-mongooseim/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./stanza/examples:/usr/share/nginx/html:ro
      - ./stanza/dist:/usr/share/nginx/dist:ro
    ports:
      - 80:80
