version: "3.8"
services:
  ejabberd:
    image: ejabberd/ecs:21.01
    container_name: ejabberd
    volumes:
      - ./ejabberd/conf:/home/ejabberd/conf:ro
      - ./ejabberd/logs:/home/ejabberd/logs
      - ./ejabberd/database:/home/ejabberd/database
    restart: always
    ports:
      - 3478:3478
      - 5443:5443
      - 5281:5281
      - 5280:5280
      - 5222:5222
      - 5269:5269
      - 1883:1883
  nginx:
    depends_on:
      - ejabberd
    image: nginx:1.19
    container_name: was
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./stanza/examples:/usr/share/nginx/html:ro
      - ./stanza/dist:/usr/share/nginx/dist:ro
    ports:
      - 80:80
